name: attado_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  android_id: ^0.3.6
  android_intent_plus: ^4.0.3
  badges: ^3.1.1
  cross_file: ^0.3.3+5
  device_info_plus: ^9.1.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^12.1.1
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.2.0
  intl: ^0.18.1
  local_auth: ^2.1.7
  logger: ^2.0.2+1
  maps_launcher: ^2.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  toastification: ^1.1.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.3.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon.png

